name: recibo_pro
description: "Gerador de recibos PDF para autônomos brasileiros."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.0
  sqflite: ^2.3.0
  path_provider: ^2.1.0
  path: ^1.9.0
  pdf: ^3.10.0
  printing: ^5.12.0
  google_fonts: ^6.2.0
  shared_preferences: ^2.2.0
  intl: ^0.20.2
  image_picker: ^1.0.7
  google_sign_in: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
